### ISSUE TITLE
SyntaxError: await is only valid in async function

### ISSUE THREAD

**Issue by nubovik01** [zispidd/discord_demotivator_bot#3]
Вот код:

const Discord = require("discord.js");
const demotivator = require("../modules/demotivator")
const bc = require("../botconfig.json");

module.exports.run = async (bot, message) => {
    const args = message.content.split(" ").slice(1).join(" ");

    if (!args[0] || !args[1]) {
        return message.reply("укажи текст через пробел, пример: **f!demotivator текст1 текст2**")
    };

    if (message.attachments.size > 0) {
        message.attachments.forEach(attachment => {
            const photourl = attachment.url;

            message.reply("создаю...").then(msg => {
                msg.delete({ timeout: 1000 });
            });

            const image = await demotivator(photourl, args[0], args[1])
            message.channel.send({ files: [image] });
        });
    } else {
        message.reply("вы забыли прикрепить фотографию к сообщению.")
    }
}

module.exports.help = {
    name: "demotivator"
}

модулъ: 
const { createCanvas, loadImage } = require('canvas')
const bg = "files/demotivator.png"

const imageProperties = {
  width: 714,
  height: 745
}

const canvas = createCanvas (imageProperties.width, imageProperties.height)

const demotivatorImage = async (img, title, subtitle) => {
  const ctx = canvas.getContext('2d')
  ctx.font = '48px Times New Roman'

  const image = await loadImage(bg)
  ctx.drawImage(image, 0, 0)
  const avatar = await loadImage(img.attachment)
  ctx.drawImage(avatar, 46, 46, 622, 551)

  ctx.fillStyle = '#fff'
  ctx.textAlign = 'center'
  ctx.fillText(title, 345, 660)

  ctx.font = 'normal 40px Times New Roman'
  ctx.fillStyle = '#fff'
  ctx.textAlign = 'center'
  ctx.fillText(subtitle, 345, 705)

  const buffer = canvas.toBuffer('image/png')
  return buffer
}

module.exports = demotivatorImage

пишет ошибку **SyntaxError: await is only valid in async function**. Помогите :(

**Comment by nubovik01** [comment]
плиз(

**Comment by nubovik01** [comment]
уже не надо, у меня всё заработало.

**Comment by zispidd** [comment]
Был занят и не видел, рад что все работает!
